### ISSUE TITLE
建议在spread_data对象里加上对合约手续费的合并计算

### ISSUE THREAD

**Issue by Mjzs12138** [vnpy/vnpy_spreadtrading#24]
设置交易手续费rate的时候，因为价差有方向，而且价差本身不考虑size，因此直接指定rate=0.0001的时候，不仅手续费可能是负的，而且绝对值还很小。那么手续费似乎只能跟滑点合并到一起设置。我反馈一下这个问题，建议后期在spreadData 对象里加上对合约手续费的合并计算

**Comment by vnpy** [comment]
感谢反馈，这块我们在后续的SpreadTrading模块优化中来完善

**Comment by noranhe** [comment]
可以去看一下back testing.py的calculate_pnl函数。commssion的计算是累加turnover乘以rate，因为turnover是取的trade.volume（正数） * size * trade.value，所以turnover也只会是正数，那么手续费计算就不会是负的。
