### ISSUE TITLE
增加动态调整价差参数的功能

### ISSUE THREAD

**Issue by Mjzs12138** [vnpy/vnpy_spreadtrading#25]
跨品种价差的配比系数经常变动的，回测期比较长时更需要动态计算配比系数。期待vnpy_spreadtrading将来能够支持价差公式的动态调整。

**Comment by vnpy** [comment]
这块可以通过分段回测拼接最终绩效DataFrame来实现，不需要修改价差本身了，每一段创建一个新的价差对象即可。
